swagger: '2.0'
info:
  description: Api Doc for syncing with The Eye. The following APIs can be hit to send data that will be crunched by The Eye to create inferences that will be shown on you own custom eye domain.
  version: 1.0.7
  title: Datacove API
  termsOfService: http://swagger.io/terms/
  contact:
    email: info@delium.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: datacove.delium.io
basePath: /
tags:
  - name: master
    description: Master info. Completely pulled one very sync
  - name: transactional
    description: Transactional data. Completely pulled if required on a flag. By default, only new info is to be sent for these APIs. Use timestamps to identify the delta of data.
schemes:
  - https
paths:
  /wastages:
    $ref: 'paths/wastages.yaml'
  /purchase_returns:
    $ref: 'paths/purchase_returns.yaml'
securityDefinitions:
  api_key:
    type: apiKey
    name: SYNC-TOKEN
    in: header
definitions:
  SyncResponse:
    $ref: 'components/responses/success_response.yaml'
  UniqueViolationSyncResponse:
    $ref: 'components/responses/constraint_violation_response.yaml'
  Wastages:
    $ref: 'components/data_formats/wastages.yaml'
  PurchaseReturns:
    $ref: 'components/data_formats/purchase_returns.yaml'
        

